apiVersion: v1
kind: Namespace
metadata:
  name: "2401195"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trustvote-frontend-deployment
  namespace: "2401195"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trustvote-frontend
  template:
    metadata:
      labels:
        app: trustvote-frontend
    spec:
      imagePullSecrets:
        - name: nexus-secret
      containers:
      - name: trustvote-frontend
        image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/pavan-project/trustvote-frontend:v13
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: trustvote-frontend-service
  namespace: "2401195"
spec:
  selector:
    app: trustvote-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 5000
  type: ClusterIP
